### ISSUE TITLE
Journal's executor service should be bounded

### ISSUE THREAD

**Issue by gehel** [blazegraph/database#91]
The Blazegraph instances we are running for [Wikidata Query Service](https://query.wikidata.org/) see a somewhat spiky load. This leads to the [`ServiceExecutor` backing the Blazegraph Journal](https://github.com/blazegraph/database/blob/master/bigdata-core/bigdata/src/java/com/bigdata/journal/Journal.java#L283-L286) to create and destroy threads at a fairly high rate. This seems to be mainly wasting resources, thousands of threads will not process faster when bound by CPU and IO available on the servers.

I have a [tentative patch for this](https://gerrit.wikimedia.org/r/#/c/wikidata/query/blazegraph/+/433724/3/bigdata-core/bigdata/src/java/com/bigdata/journal/Journal.java), applied to our fork of Blazegraph. I have not yet deployed and tested this approach, but feedback from people who know that code would be more than welcomed! If there is any interest, I can send this as a PR on github as well.

**Comment by thompsonbry** [comment]
Guillaume,

Blazegraph uses within query parallelism and a blocking queue in front of
each operator.  Since that queue can fill before the upstream operator is
done, Blazegraph will deadlock if you bound the Journal's executor
service.  If you make the queue unbounded, then you can restrict the kinds
of queries which blazegraph can execute successfully (it will often fill up
a queue because a downstream operator is slower, then lunch multiple
instances of the downstream operator to accelerate that part of the query).

There are upsides and downsides to the BG query design.  Upsides include
significant ability for latency hiding (e.g., IO latency) during query
execution, the ability to drive a lot of read IOs for query, and the
ability to flex the amount of compute resources on a given query.

I would recommend that you bound the #of queries that can launch
concurrently, the amount of memory per query, and the time per query.
Blazegraph exposes mechanisms for each of those things.  Stas (Cc) can help
you find the appropriate configuration knobs (web.xml I believe).

Thanks,
Bryan

**Comment by gehel** [comment]
Damn, I was worried of some kind of deadlocks introduced in my patch. I'll dig a bit more into the other knobs that might help and check with Stas.
